on:
  push:
    branches:
      [ main, github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: test secrets
        shell: bash
        env:
          ECHO_SECRET: ${{ WHO_AM_I }}
        run: |
            echo $ECHO_SECRET
      - name: build with maven
        run: mvn -DskipTests package
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-artifact
          path: target/*.jar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: built-artifact
          path: target
      - name: Run tests
        run: mvn verify